version: "3.8"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    networks:
      - skywalker-network
    deploy:
      replicas: 2

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    networks:
      - skywalker-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
    networks:
      - skywalker-network

networks:
  skywalker-network:
    driver: bridge
