version: "3.8"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    networks:
      - skywalker

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end
    networks:
      - skywalker

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - skywalker

networks:
  skywalker:
    driver: bridge
